# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#plist文件路径
INFO_PLIST_FILE_PATH = './XLLJenkinsDemo/Info.plist'

platform :ios do
  desc "自动化打AdHoc包"
  lane :AdHoc do |options|
    gym(
      Scheme: ""
    )
  end
end
